In [1]:
import numpy as np
import pandas as pd

# Viz
from matplotlib import pyplot as plt
import seaborn as sns

# Pretty plots
plt.style.use('seaborn-v0_8')
sns.set_context('notebook')

# Pandas display
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

In [3]:
df = pd.read_csv('./data/Passenger_Counts.csv')
print(f'Rows, Columns:\n{df.shape}')
df.head()

Rows, Columns:
(1330305, 7)

   OBJECTID Route_Number       Route_Name  Ridership_Total  Route_Hour Route_Hour_Description            Route_Date
0         1           7A        Peninsula               21        13.0       1:00pm to 1:29pm  1/1/2024 10:00:00 AM
1         2           7B        Peninsula               32        13.0       1:00pm to 1:29pm  1/1/2024 10:00:00 AM
2         3           88  Bedford Commons                5        13.0       1:00pm to 1:29pm  1/1/2024 10:00:00 AM
3         4            1    Spring Garden              184        13.5       1:30pm to 1:59pm  1/1/2024 10:00:00 AM
4         5            2         Fairview               57        13.5       1:30pm to 1:59pm  1/1/2024 10:00:00 AM

In [4]:
df.dtypes

OBJECTID                    int64
Route_Number               object
Route_Name                 object
Ridership_Total             int64
Route_Hour                float64
Route_Hour_Description     object
Route_Date                 object
dtype: object

In [5]:
df.columns

Index(['OBJECTID', 'Route_Number', 'Route_Name', 'Ridership_Total', 'Route_Hour', 'Route_Hour_Description',
       'Route_Date'],
      dtype='object')

In [6]:
df['Route_Number'].unique()

array(['7A', '7B', '88', '1', '2', '21', '25', '30B', '4', '5', '55',
       '68', '6B', '8', '82', '83', '87', '90', '9A', '10', '29', '3',
       '30A', '39', '56', '61', '63', '67', '6C', '72', '85', '86', '22',
       '84', '91', '24', '320', '58', '65', '54', '59', '28', '127',
       '137', '158', '159', '161', '165', '168B', '182', '183', '185',
       '194', '330', '370', '433', '50', '6A', '93', '9B', '135', '186',
       '415', '53', '57', '401', '51B', '64', '51A', '62', '168A', '136',
       '138', '123', '196', '26', '192', '10A', '10B', '10C'],
      dtype=object)

In [7]:
route_prefixes = ('1', '2', '3', '4', '5')
filtered_df1 = df[df['Route_Number'].astype(str).str.startswith(route_prefixes)]

In [8]:
filtered_df1.shape

(739583, 7)

In [9]:
route_prefixes = ('6', '7', '8', '9', '0')
filtered_df2 = df[df['Route_Number'].astype(str).str.startswith(route_prefixes)]

In [10]:
filtered_df2

,OBJECTID,Route_Number,Route_Name,Ridership_Total,Route_Hour,Route_Hour_Description,Route_Date
0,1,7A,Peninsula,21,13.0,1:00pm to 1:29pm,1/1/2024 10:00:00 AM
1,2,7B,Peninsula,32,13.0,1:00pm to 1:29pm,1/1/2024 10:00:00 AM
2,3,88,Bedford Commons,5,13.0,1:00pm to 1:29pm,1/1/2024 10:00:00 AM
11,12,68,Cherry Brook,3,13.5,1:30pm to 1:59pm,1/1/2024 10:00:00 AM
12,13,6B,Eastern Passage,21,13.5,1:30pm to 1:59pm,1/1/2024 10:00:00 AM
...,...,...,...,...,...,...,...
1330289,1330290,7A,Peninsula,0,9.5,9:30am to 9:59am,11/30/2025 10:00:00 AM
1330290,1330291,7B,Peninsula,27,9.5,9:30am to 9:59am,11/30/2025 10:00:00 AM
1330291,1330292,84,Glendale Express,10,9.5,9:30am to 9:59am,11/30/2025 10:00:00 AM
1330292,1330293,86,Beaver Bank,3,9.5,9:30am to 9:59am,11/30/2025 10:00:00 AM
1330304,1330305,61,North Preston,7,10.0,10:00am to 10:29am,11/30/2025 10:00:00 AM

In [11]:
filtered_df1.shape[0] + filtered_df2.shape[0]

1330305

In [12]:
df.shape[0]

1330305

In [13]:
filtered_df1.to_csv('Ridership1.csv', index=False)

In [14]:
filtered_df2.to_csv('Ridership2.csv', index=False)